project:
  type: website
  output-dir: docs # setting the output directory to docs
  resources: 
    - media/**

website:
  title: "Mark Oregel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About me
        menu: 
          - text: Section 1 
            href: Section1.qmd
          - text: Section 2
            href: Section2.qmd
          - text: Section 3
            href: Section3.qmd

format:
  html:
    theme:
      light: zephyr
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

